feat: send flag decisions
optimizely/ruby-sdk pull request #272
Opened 2020-10-12 15:47 UTC by oakbani

## Summary
- Dispatches event when rollout and send_flag_deciions flag is True
- Dispatches event when variation is nil ( neither feature-test nor rollout) and send_flag_decisions is True
- Adds metadata to impression event. 

## Test plan
- Fixed All Unit tests
- Verified Manually with FSC Flag Decisions Tests

## Issues

2020-10-12 16:36 UTC, pawels-optimizely requested changes

2020-10-12 16:36 UTC, pawels-optimizely commented on lib/optimizely.rb
> +        config, experiment, variation_key, experiment_key, experiment_key,
why are we passing experiment key twice ?

2020-10-12 16:36 UTC, pawels-optimizely commented on spec/project_spec.rb
> +                flag_key: 'test_experiment',
this is never possible when flag_key is rule_key

2020-10-12 16:36 UTC, pawels-optimizely commented on spec/project_spec.rb
> +        flag_key: 'test_experiment_with_audience',
same comment as before

2020-10-13 06:10 UTC, oakbani commented
@pawels-optimizely  As discussed, 
- now activate will pass empty string for flag key
- is_feature_enabled will pass empty string for rule key and variation key and rollout in rule type when variation is nil.

2020-10-13 19:25 UTC, msohailhussain approved these changes
lgtm

2020-10-20 20:15 UTC, pawels-optimizely approved these changes
lgtm

2020-10-20 20:18 UTC, pawels-optimizely requested changes
please address my comments

2020-10-21 18:18 UTC, pawels-optimizely approved these changes
lgtm, thx for addressing the comments

2020-10-21 18:18 UTC, merged