Feat: added SDKkey and environment in datafile
optimizely/ruby-sdk pull request #281
Opened 2021-06-08 06:45 UTC by ozayr-zaviar

## Summary
- Sdk key and environment keys are going to be parse in sdk and will be sent back in optimizelyConfig

## Test plan
All unit tests and FSC tests should pass

2021-06-15 21:44 UTC, msohailhussain commented on lib/optimizely/config/datafile_project_config.rb
> +    attr_reader :sdk_key
update header.

2021-06-16 21:07 UTC, zashraf1985 requested changes

2021-06-16 21:07 UTC, zashraf1985 commented on lib/optimizely/config/datafile_project_config.rb
> +    def get_sdk_key()
why create these getters when you have already declared read only attributes and using those directly?

2021-06-22 22:18 UTC, msohailhussain approved these changes
lgtm

2021-06-22 22:18 UTC, merged