feat(OptimizelyConfig): Add new fields to OptimizelyConfig
optimizely/ruby-sdk pull request #285
Opened 2021-07-29 13:12 UTC by ozayr-zaviar

## Summary
The following new public properties are added to OptimizelyConfig:
- sdkKey
- environmentKey
- attributes
- audiences
- events
- experimentRules and deliveryRules to OptimizelyFeature
- audiences to OptimizelyExperiment

## Test plan
All FSC tests OPTIMIZELY_CONFIG_V2 tests should pass.

2021-08-04 21:19 UTC, msohailhussain commented on lib/optimizely/optimizely_config.rb
> +        next unless old_audience['id'] != '$opt_dummy_audience'
not sure, this is the right assumption. it may come in the middle of the array.

2021-08-04 21:20 UTC, msohailhussain commented on lib/optimizely/optimizely_config.rb
> +          'conditions' => type_audience['conditions'].to_json
this should be `string`

2021-08-04 21:21 UTC, msohailhussain commented on lib/optimizely/optimizely_config.rb
> +        'sdk_key' => @project_config.sdk_key,
sdkKey

2021-08-04 21:21 UTC, msohailhussain commented on lib/optimizely/optimizely_config.rb
> +        'environment_key' => @project_config.environment_key
should be camelcase.

2021-08-05 23:40 UTC, zashraf1985 requested changes

2021-08-05 23:40 UTC, zashraf1985 commented on lib/optimizely/optimizely_config.rb
> +      id_lookup_dict = {}
I assume it holds audiences only, if yes, the name should reflect that.

2021-08-05 23:40 UTC, zashraf1985 commented on lib/optimizely/optimizely_config.rb
> +      optly_typed_audiences = []
whats the differece between `type_audiences` and `optly_typed_audiences`. It should be clear from the variable names that why there are two arrays being used. Actually you dont even need to use `type_audiences` one. You can use `#project_config.typed_audiences` directly to loop below. `optly_typed_audiences` does not sound consistent with others as no other variable are prefixed with `optly`. You should use `typed_audiences` to hold temp audiences and directly reference `@project_config.typed_audiences` to loop through the original array.

2021-08-05 23:40 UTC, zashraf1985 commented on lib/optimizely/optimizely_config.rb
> +      experiments_key_map
Tou could probably use reduce here?

2021-08-11 01:06 UTC, keppel2 commented
A passing continuous integration (CI) can be helpful for reviews, but I will check to see if there is anything I can help with.

2021-08-11 01:06 UTC, keppel2 commented on lib/optimizely/optimizely_config.rb
> +#         variation_object['featureEnabled'] = variation['featureEnabled'] if @project_config.feature_experiment?(experiment['id']) || @project_config.rollout_experiment?(experiment['id'])
Remove.

2021-08-11 01:18 UTC, keppel2 commented
`rkeppel@unknown- ruby-sdk % rubocop
Inspecting 85 files
.............................................C..............................C.....C..

Offenses:

lib/optimizely/optimizely_config.rb:109:1: C: Layout/CommentIndentation: Incorrect indentation detected (column 0 instead of 8).
#         variation_object['featureEnabled'] = variation['featureEnabled'] if @project_config.feature_experiment?(experiment['id']) || @project_config.rollout_experiment?(experiment['id'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/optimizely_config_spec.rb:764:1: C: Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.
spec/spec_params.rb:1428:8: C: Layout/MultilineArrayBraceLayout: The closing array brace must be on the line after the last array element when the opening brace is on a separate line from the first array element.
      }],
       ^

85 files inspected, 3 offenses detected
rkeppel@unknown- ruby-sdk % echo $?
1
`

2021-08-11 01:19 UTC, keppel2 commented
```
rkeppel@unknown- ruby-sdk % rubocop
Inspecting 85 files
.............................................C..............................C.....C..

Offenses:

lib/optimizely/optimizely_config.rb:109:1: C: Layout/CommentIndentation: Incorrect indentation detected (column 0 instead of 8).
#         variation_object['featureEnabled'] = variation['featureEnabled'] if @project_config.feature_experiment?(experiment['id']) || @project_config.rollout_experiment?(experiment['id'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/optimizely_config_spec.rb:764:1: C: Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.
spec/spec_params.rb:1428:8: C: Layout/MultilineArrayBraceLayout: The closing array brace must be on the line after the last array element when the opening brace is on a separate line from the first array element.
      }],
       ^

85 files inspected, 3 offenses detected
rkeppel@unknown- ruby-sdk % echo $?
1

```

2021-08-11 01:21 UTC, keppel2 commented on lib/optimizely/optimizely_config.rb
> +#         variation_object['featureEnabled'] = variation['featureEnabled'] if @project_config.feature_experiment?(experiment['id']) || @project_config.rollout_experiment?(experiment['id'])
It looks like doing so will help with `rubocop`.

2021-08-11 01:23 UTC, keppel2 commented
```
diff --git a/lib/optimizely/optimizely_config.rb b/lib/optimizely/optimizely_config.rb
index 6537ccc..9226ea9 100644
--- a/lib/optimizely/optimizely_config.rb
+++ b/lib/optimizely/optimizely_config.rb
@@ -106,7 +106,6 @@ module Optimizely
           'featureEnabled' => variation['featureEnabled'],
           'variablesMap' => get_merged_variables_map(variation, feature_id, feature_variables_map)
         }
-#         variation_object['featureEnabled'] = variation['featureEnabled'] if @project_config.feature_experiment?(experiment['id']) || @project_config.rollout_experiment?(experiment['id'])
         variations_map.update(variation['key'] => variation_object)
       end
     end
diff --git a/spec/optimizely_config_spec.rb b/spec/optimizely_config_spec.rb
index a0b372a..07ba5ae 100644
--- a/spec/optimizely_config_spec.rb
+++ b/spec/optimizely_config_spec.rb
@@ -761,7 +761,6 @@ describe Optimizely::OptimizelyConfig do
       result = optimizely_config.send(:replace_ids_with_names, audience_condition, audiences_map)
       expect(result).to eq(expected_audience_outputs[index])
     end
-
   end
 
   it 'should return correct config revision' do
diff --git a/spec/spec_params.rb b/spec/spec_params.rb
index eab7ad8..4647f4e 100644
--- a/spec/spec_params.rb
+++ b/spec/spec_params.rb
@@ -1425,7 +1425,8 @@ module OptimizelySpec
         'variables' => [],
         'id' => '2027',
         'key' => 'flag_1'
-      }],
+      }
+    ],
     'experiments' => [],
     'audiences' => [
       {

```
This seems to quiet `rubocop`.

2021-08-11 05:07 UTC, msohailhussain commented
> `rubocop` worked for me on my MacBook. You can run it before pushing in changes to see if it will pass.

that should be part of separate PR. Feel free to format and open a new PR. This is mostly related to optimizely_config, it will be difficult for reviewers to review the actual changes if formatting changes are placed in the same PR.

2021-08-11 08:32 UTC, keppel2 commented
FEATURE_ENABLED is a known issue @msohailhussain .

2021-08-11 08:34 UTC, keppel2 commented
Looks good--nice job with passing the PR tests.

2021-08-11 08:38 UTC, keppel2 commented
Fullstack-prod-suite seems stuck in travis. Another push may wake it up.

2021-08-11 13:24 UTC, The-inside-man commented on lib/optimizely/optimizely_config.rb
> +    def stringify_conditions(conditions, audiences_map)
Do we have any test cases for this? Just to confirm functionality.

2021-08-11 14:20 UTC, zashraf1985 approved these changes
LGTM! Added a few more minor comments. Preapproving based on the assumption that those comments will be addressed before merging

2021-08-11 18:17 UTC, jaeopt approved these changes
LGTM 
A couple of comments about deprecation suggested.

2021-08-11 20:06 UTC, jaeopt commented on lib/optimizely/optimizely_config.rb
>          'experimentsMap' => experiments_map_object,
Need a period at the end of the first sentence - "This experimentsMap is for experiments of legacy projects only"

2021-08-11 22:32 UTC, keppel2 approved these changes

2021-08-12 18:33 UTC, jaeopt requested changes
Deprecation message should be changed

2021-08-12 18:33 UTC, jaeopt commented on lib/optimizely/optimizely_config.rb
> +            # when keys conflict. Use experimentRules and deliveryRules instead.
This message should be chanaged to: 
"This experimentsMap is deprecated. Use experimentRules and deliveryRules instead."

The one at top level ("experimentsMap" in OptimizleyConfig) looks good.

2021-08-12 22:24 UTC, jaeopt approved these changes
LGTM

2021-08-12 23:43 UTC, merged