refactor: moved validated forced decision to decision service.
optimizely/ruby-sdk pull request #293
Opened 2021-12-22 09:36 UTC by ozayr-zaviar

Summary
-------
- `find_validated_forced_decision` moved to decision service.

Test plan
---------
- All unit tests and FSC should pass.

2021-12-29 08:03 UTC, yasirfolio3 requested changes

2021-12-29 08:03 UTC, yasirfolio3 commented on lib/optimizely.rb
> +      variation, reasons_received = @decision_service.validated_forced_decision(context, user_context)
please keep the method name `find_validated_forced_decision`

2021-12-29 08:03 UTC, yasirfolio3 commented on lib/optimizely/decision_service.rb
> +      rule_key = context[:rule_key]
can we move this code inside the if block since it is only used there?

2021-12-29 08:03 UTC, yasirfolio3 commented on lib/optimizely/decision_service.rb
> +          return variation, reasons
this code can be moved to line 436, that way we won't have `reasons.push(reason)` twice.

2021-12-29 08:03 UTC, yasirfolio3 commented on lib/optimizely/optimizely_user_context.rb
> +    attr_reader :optimizely_client
why is this needed when we are only removing a method here?

2021-12-29 08:05 UTC, yasirfolio3 requested changes

2021-12-29 08:05 UTC, yasirfolio3 commented on lib/optimizely/optimizely_user_context.rb
> +    attr_reader :optimizely_client
Also update the Copyright header with `2020-2021`

2022-01-06 01:05 UTC, jaeopt requested changes
A couple of changes suggested

2022-01-06 01:05 UTC, jaeopt commented on lib/optimizely/decision_service.rb
> +      decision = user_context.find_forced_decision(context)
Remove `find_forced_decision` and use `get_forced_decision`. Since we remove sanity checking, they're now identical.

2022-01-06 17:32 UTC, jaeopt requested changes
See comments

2022-01-06 17:32 UTC, jaeopt commented on lib/optimizely/decision_service.rb
> +        variation = user_context.optimizely_client.get_flag_variation(flag_key, variation_key, 'key')
I don't what happened to my previous comments on this line. github bug? :)
We need to change this line to same as other SDKs - pass 'config' as a parameter and move `get_flag_variation` to `config`, so we can remove dependency to `user_context.optimizely_client` here.

2022-01-06 21:01 UTC, jaeopt approved these changes
LGTM

2022-01-07 06:03 UTC, yasirfolio3 approved these changes

2022-01-07 06:03 UTC, merged