chore: removed travis yml and added git action support
optimizely/ruby-sdk pull request #300
Opened 2022-04-13 13:32 UTC by ozayr-zaviar

## Summary
- We remove travis yaml from ruby-sdk and moved all the stages to git action.

NOTE:
Please update [this](https://github.com/optimizely/ruby-sdk/blob/21005c3085d670e6b3b9c2993ac194163c146c0d/.github/workflows/ruby.yml#L11), [this](https://github.com/optimizely/ruby-sdk/blob/21005c3085d670e6b3b9c2993ac194163c146c0d/.github/workflows/ruby.yml#L14) and [this](https://github.com/optimizely/ruby-sdk/blob/21005c3085d670e6b3b9c2993ac194163c146c0d/.github/workflows/ruby.yml#L20) line branch name to master before merging.

## Test plan
All tests should pass

2022-04-15 23:38 UTC, jaeopt approved these changes
LGTM

2022-04-22 06:24 UTC, msohailhussain requested changes
please address.

2022-04-22 06:25 UTC, msohailhussain requested changes
please address.

2022-04-22 16:12 UTC, jaeopt approved these changes
LGTM

2022-04-22 16:13 UTC, ozayr-zaviar commented on optimizely-sdk.gemspec
> +  spec.add_development_dependency 'coveralls_reborn'
Coveralls is last updated on Sep 9, 2021 and a newer and updated fork is coveralls_reborn. Coveralls is also not supported with git actions.

2022-04-28 20:37 UTC, msohailhussain approved these changes
lgtm

2022-04-28 20:38 UTC, msohailhussain commented on .github/workflows/ruby.yml
> +    uses: optimizely/ruby-sdk/.github/workflows/integration_test.yml@uzair/master
```suggestion
    uses: optimizely/ruby-sdk/.github/workflows/integration_test.yml@master
```

2022-04-28 20:39 UTC, msohailhussain commented on .github/workflows/ruby.yml
> +    uses: optimizely/ruby-sdk/.github/workflows/integration_test.yml@uzair/master
```suggestion
    uses: optimizely/ruby-sdk/.github/workflows/integration_test.yml@master
```

2022-04-28 20:41 UTC, merged